//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package jadx.plugins.linter.xmlbinding;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for itemType complex type
 * </p>
 * .
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * </p>
 *
 * <pre>{@code
 * <complexType name="itemType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="annotation" type="{}annotationType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
		name = "itemType", propOrder = {
				"annotation"
		}
)
public class ItemType {

	protected List<AnnotationType> annotation;
	@XmlAttribute(name = "name")
	protected String name;

	/**
	 * Gets the value of the annotation property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the annotation property.
	 * </p>
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * </p>
	 *
	 * <pre>
	 * getAnnotation().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AnnotationType }
	 * </p>
	 *
	 *
	 * @return
	 *         The value of the annotation property.
	 */
	public List<AnnotationType> getAnnotation() {
		if (annotation == null) {
			annotation = new ArrayList<>();
		}
		return this.annotation;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return
	 *         possible object is
	 *         {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *              allowed object is
	 *              {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	public void setAnnotation(List<AnnotationType> annotation) {
		this.annotation = annotation;
	}
}
